// backend/scripts/exercises/python-workbook-chapter1.ts
// Python Workbook - Chapter 1: 10 exercises × 4 languages = 40 entries.

export const pythonWorkbookChapter1 = [
  // Ex1: Mailing Address - Python
  {
    title: 'Python Workbook Ch1-Ex1: Mailing Address',
    description: 'Print a complete name and mailing address (4+ lines)',
    difficulty: 'easy',
    language: 'python',
    category: 'strings',
    keywords: ['output', 'print'],
    tags: ['python-workbook', 'chapter-1', 'exercise-1'],
    testCases: [{ input: null, expectedOutput: null, description: 'Print 4+ lines' }],
    solution: 'print("Alex Morgan")\nprint("123 Main Street")\nprint("New York, NY 10001")\nprint("United States")',
    starterCode: '# Print the address\n# Your code here\n',
    hints: ['Use print()', 'Print at least 4 lines'],
  },
  // Ex1: Mailing Address - JavaScript
  {
    title: 'Python Workbook Ch1-Ex1: Mailing Address',
    description: 'Print a complete name and mailing address (4+ lines)',
    difficulty: 'easy',
    language: 'javascript',
    category: 'strings',
    keywords: ['output', 'console.log'],
    tags: ['python-workbook', 'chapter-1', 'exercise-1'],
    testCases: [{ input: null, expectedOutput: null, description: 'Print 4+ lines' }],
    solution: 'console.log("Alex Morgan");\nconsole.log("123 Main Street");\nconsole.log("New York, NY 10001");\nconsole.log("United States");',
    starterCode: '// Print the address\n// Your code here\n',
    hints: ['Use console.log()', 'Print at least 4 lines'],
  },
  // Ex1: Mailing Address - Java
  {
    title: 'Python Workbook Ch1-Ex1: Mailing Address',
    description: 'Print a complete name and mailing address (4+ lines)',
    difficulty: 'easy',
    language: 'java',
    category: 'strings',
    keywords: ['output', 'System.out.println'],
    tags: ['python-workbook', 'chapter-1', 'exercise-1'],
    testCases: [{ input: null, expectedOutput: null, description: 'Print 4+ lines' }],
    solution: 'public class MailingAddress {\n    public static void main(String[] args) {\n        System.out.println("Alex Morgan");\n        System.out.println("123 Main Street");\n        System.out.println("New York, NY 10001");\n        System.out.println("United States");\n    }\n}',
    starterCode: 'public class MailingAddress {\n    public static void main(String[] args) {\n        // Your code here\n    }\n}',
    hints: ['Use System.out.println()', 'Print at least 4 lines'],
  },
  // Ex1: Mailing Address - C++
  {
    title: 'Python Workbook Ch1-Ex1: Mailing Address',
    description: 'Print a complete name and mailing address (4+ lines)',
    difficulty: 'easy',
    language: 'cpp',
    category: 'strings',
    keywords: ['output', 'cout'],
    tags: ['python-workbook', 'chapter-1', 'exercise-1'],
    testCases: [{ input: null, expectedOutput: null, description: 'Print 4+ lines' }],
    solution: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Alex Morgan" << endl;\n    cout << "123 Main Street" << endl;\n    cout << "New York, NY 10001" << endl;\n    cout << "United States" << endl;\n    return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // Your code here\n    return 0;\n}',
    hints: ['Use cout', 'Print at least 4 lines'],
  },

  // Ex2: Hello - Python
  {
    title: 'Python Workbook Ch1-Ex2: Hello',
    description: 'Reads user\'s name and greets with "Hello [name]"',
    difficulty: 'easy',
    language: 'python',
    category: 'strings',
    keywords: ['input', 'output'],
    tags: ['python-workbook', 'chapter-1', 'exercise-2'],
    testCases: [{ input: 'Alice', expectedOutput: 'Hello Alice', description: 'Greet Alice' }],
    solution: 'name = input("Name: ")\nprint("Hello", name)',
    starterCode: '# Read the name and greet\nname = input("Name: ")\n# Your code here\n',
    hints: ['Use input()', 'Combine text'],
  },
  // Ex2: Hello - JavaScript
  {
    title: 'Python Workbook Ch1-Ex2: Hello',
    description: 'Reads user\'s name and greets with "Hello [name]"',
    difficulty: 'easy',
    language: 'javascript',
    category: 'strings',
    keywords: ['input', 'readline'],
    tags: ['python-workbook', 'chapter-1', 'exercise-2'],
    testCases: [{ input: 'Alice', expectedOutput: 'Hello Alice', description: 'Greet Alice' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("Name: ", (name) => {\n    console.log("Hello", name);\n    rl.close();\n});',
    starterCode: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\n// Your code here\n',
    hints: ['Use readline', 'Combine text'],
  },
  // Ex2: Hello - Java
  {
    title: 'Python Workbook Ch1-Ex2: Hello',
    description: 'Reads user\'s name and greets with "Hello [name]"',
    difficulty: 'easy',
    language: 'java',
    category: 'strings',
    keywords: ['input', 'Scanner'],
    tags: ['python-workbook', 'chapter-1', 'exercise-2'],
    testCases: [{ input: 'Alice', expectedOutput: 'Hello Alice', description: 'Greet Alice' }],
    solution: 'import java.util.Scanner;\n\npublic class Hello {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.print("Name: ");\n        String name = sc.nextLine();\n        System.out.println("Hello " + name);\n        sc.close();\n    }\n}',
    starterCode: 'import java.util.Scanner;\n\npublic class Hello {\n    public static void main(String[] args) {\n        // Your code here\n    }\n}',
    hints: ['Use Scanner', 'nextLine()'],
  },
  // Ex2: Hello - C++
  {
    title: 'Python Workbook Ch1-Ex2: Hello',
    description: 'Reads user\'s name and greets with "Hello [name]"',
    difficulty: 'easy',
    language: 'cpp',
    category: 'strings',
    keywords: ['input', 'cin'],
    tags: ['python-workbook', 'chapter-1', 'exercise-2'],
    testCases: [{ input: 'Alice', expectedOutput: 'Hello Alice', description: 'Greet Alice' }],
    solution: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string name;\n    cout << "Name: ";\n    getline(cin, name);\n    cout << "Hello " << name << endl;\n    return 0;\n}',
    starterCode: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // Your code here\n    return 0;\n}',
    hints: ['Use getline()', 'string'],
  },

  // Ex3: Area of a Room - Python
  {
    title: 'Python Workbook Ch1-Ex3: Area of a Room',
    description: 'Calculate the room area (width × length)',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['arithmetic', 'area'],
    tags: ['python-workbook', 'chapter-1', 'exercise-3'],
    testCases: [{ input: '5\n10', expectedOutput: '50', description: '5×10=50' }],
    solution: 'w = float(input("Width: "))\nl = float(input("Length: "))\nprint("Area:", w*l)',
    starterCode: '# Room area\n# Your code here\n',
    hints: ['Read two numbers', 'area=width×length'],
  },
  // Ex3: Area of a Room - JavaScript
  {
    title: 'Python Workbook Ch1-Ex3: Area of a Room',
    description: 'Calculate the room area (width × length)',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['arithmetic', 'parseFloat'],
    tags: ['python-workbook', 'chapter-1', 'exercise-3'],
    testCases: [{ input: '5\n10', expectedOutput: '50', description: '5×10=50' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("Width: ", (w) => {\n    rl.question("Length: ", (l) => {\n        console.log("Area:", parseFloat(w)*parseFloat(l));\n        rl.close();\n    });\n});',
    starterCode: '// Room area\n// Your code here\n',
    hints: ['parseFloat()', 'area=width×length'],
  },
  // Ex3: Area of a Room - Java
  {
    title: 'Python Workbook Ch1-Ex3: Area of a Room',
    description: 'Calculate the room area (width × length)',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['arithmetic', 'double'],
    tags: ['python-workbook', 'chapter-1', 'exercise-3'],
    testCases: [{ input: '5\n10', expectedOutput: '50', description: '5×10=50' }],
    solution: 'import java.util.Scanner;\n\npublic class RoomArea {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double w = sc.nextDouble();\n        double l = sc.nextDouble();\n        System.out.println("Area: " + (w*l));\n        sc.close();\n    }\n}',
    starterCode: 'import java.util.Scanner;\n\npublic class RoomArea {\n    public static void main(String[] args) {\n        // Your code here\n    }\n}',
    hints: ['nextDouble()', 'area=width×length'],
  },
  // Ex3: Area of a Room - C++
  {
    title: 'Python Workbook Ch1-Ex3: Area of a Room',
    description: 'Calculate the room area (width × length)',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['arithmetic', 'double'],
    tags: ['python-workbook', 'chapter-1', 'exercise-3'],
    testCases: [{ input: '5\n10', expectedOutput: '50', description: '5×10=50' }],
    solution: '#include <iostream>\nusing namespace std;\n\nint main() {\n    double w, l;\n    cin >> w >> l;\n    cout << "Area: " << (w*l) << endl;\n    return 0;\n}',
    starterCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // Your code here\n    return 0;\n}',
    hints: ['cin >> w >> l', 'area=width×length'],
  },

  // Ex4: Area of a Field - Python
  {
    title: 'Python Workbook Ch1-Ex4: Area of a Field',
    description: 'Calculate field area in acres (43,560 sq ft = 1 acre)',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['conversion', 'acres'],
    tags: ['python-workbook', 'chapter-1', 'exercise-4'],
    testCases: [{ input: '100\n435.6', expectedOutput: '1', description: '1 acre' }],
    solution: 'l = float(input("Length: "))\nw = float(input("Width: "))\nprint("Acres:", (l*w)/43560)',
    starterCode: '# 43560 sqft = 1 acre\n# Your code here\n',
    hints: ['area_sqft/43560=acres'],
  },
  // Ex4: Area of a Field - JavaScript
  {
    title: 'Python Workbook Ch1-Ex4: Area of a Field',
    description: 'Calculate field area in acres (43,560 sq ft = 1 acre)',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['conversion', 'acres'],
    tags: ['python-workbook', 'chapter-1', 'exercise-4'],
    testCases: [{ input: '100\n435.6', expectedOutput: '1', description: '1 acre' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("L: ", (l) => {\n    rl.question("W: ", (w) => {\n        console.log("Acres:", parseFloat(l)*parseFloat(w)/43560);\n        rl.close();\n    });\n});',
    starterCode: '// 43560 sqft = 1 acre\n// Your code here\n',
    hints: ['area_sqft/43560=acres'],
  },
  // Ex4: Area of a Field - Java
  {
    title: 'Python Workbook Ch1-Ex4: Area of a Field',
    description: 'Calculate field area in acres (43,560 sq ft = 1 acre)',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['conversion', 'acres'],
    tags: ['python-workbook', 'chapter-1', 'exercise-4'],
    testCases: [{ input: '100\n435.6', expectedOutput: '1', description: '1 acre' }],
    solution: 'import java.util.Scanner;\n\npublic class FieldArea {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double l = sc.nextDouble();\n        double w = sc.nextDouble();\n        System.out.println("Acres: " + ((l*w)/43560));\n        sc.close();\n    }\n}',
    starterCode: '// 43560 sqft = 1 acre\n// Your code here\n',
    hints: ['Divide by 43560'],
  },
  // Ex4: Area of a Field - C++
  {
    title: 'Python Workbook Ch1-Ex4: Area of a Field',
    description: 'Calculate field area in acres (43,560 sq ft = 1 acre)',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['conversion', 'acres'],
    tags: ['python-workbook', 'chapter-1', 'exercise-4'],
    testCases: [{ input: '100\n435.6', expectedOutput: '1', description: '1 acre' }],
    solution: '#include <iostream>\nusing namespace std;\n\nint main() {\n    double l, w;\n    cin >> l >> w;\n    cout << "Acres: " << ((l*w)/43560) << endl;\n    return 0;\n}',
    starterCode: '// 43560 sqft = 1 acre\n// Your code here\n',
    hints: ['Divide by 43560'],
  },

  // Ex5: Bottle Deposits - Python
  {
    title: 'Python Workbook Ch1-Ex5: Bottle Deposits',
    description: '<=1L: $0.10, >1L: $0.25. Calculate the total refund',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['money', 'formatting'],
    tags: ['python-workbook', 'chapter-1', 'exercise-5'],
    testCases: [{ input: '10\n5', expectedOutput: '$2.25', description: '10×0.10+5×0.25' }],
    solution: 's = int(input("Small: "))\nl = int(input("Large: "))\nprint(f"${s*0.10+l*0.25:.2f}")',
    starterCode: '# ≤1L=$0.10, >1L=$0.25\n# Your code here\n',
    hints: ['s×0.10+l×0.25', ':.2f'],
  },
  // Ex5: Bottle Deposits - JavaScript
  {
    title: 'Python Workbook Ch1-Ex5: Bottle Deposits',
    description: '<=1L: $0.10, >1L: $0.25. Calculate the total refund',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['money', 'toFixed'],
    tags: ['python-workbook', 'chapter-1', 'exercise-5'],
    testCases: [{ input: '10\n5', expectedOutput: '$2.25', description: '10×0.10+5×0.25' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("S: ", (s) => {\n    rl.question("L: ", (l) => {\n        console.log("$" + (parseInt(s)*0.10+parseInt(l)*0.25).toFixed(2));\n        rl.close();\n    });\n});',
    starterCode: '// ≤1L=$0.10, >1L=$0.25\n// Your code here\n',
    hints: ['toFixed(2)'],
  },
  // Ex5: Bottle Deposits - Java
  {
    title: 'Python Workbook Ch1-Ex5: Bottle Deposits',
    description: '<=1L: $0.10, >1L: $0.25. Calculate the total refund',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['money', 'printf'],
    tags: ['python-workbook', 'chapter-1', 'exercise-5'],
    testCases: [{ input: '10\n5', expectedOutput: '$2.25', description: '10×0.10+5×0.25' }],
    solution: 'import java.util.Scanner;\n\npublic class Bottles {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int s = sc.nextInt();\n        int l = sc.nextInt();\n        System.out.printf("$%.2f%n", s*0.10+l*0.25);\n        sc.close();\n    }\n}',
    starterCode: '// ≤1L=$0.10, >1L=$0.25\n// Your code here\n',
    hints: ['printf'],
  },
  // Ex5: Bottle Deposits - C++
  {
    title: 'Python Workbook Ch1-Ex5: Bottle Deposits',
    description: '<=1L: $0.10, >1L: $0.25. Calculate the total refund',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['money', 'setprecision'],
    tags: ['python-workbook', 'chapter-1', 'exercise-5'],
    testCases: [{ input: '10\n5', expectedOutput: '$2.25', description: '10×0.10+5×0.25' }],
    solution: '#include <iostream>\n#include <iomanip>\nusing namespace std;\n\nint main() {\n    int s, l;\n    cin >> s >> l;\n    cout << fixed << setprecision(2) << "$" << (s*0.10+l*0.25) << endl;\n    return 0;\n}',
    starterCode: '// ≤1L=$0.10, >1L=$0.25\n// Your code here\n',
    hints: ['setprecision(2)'],
  },

  // Ex6: Tax and Tip - Python
  {
    title: 'Python Workbook Ch1-Ex6: Tax and Tip',
    description: 'Calculate tax (10%) and tip (18%), then show the total',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['percentage', 'money'],
    tags: ['python-workbook', 'chapter-1', 'exercise-6'],
    testCases: [{ input: '100', expectedOutput: 'Tax: $10.00', description: '$100 meal' }],
    solution: 'm = float(input("Meal: "))\nt = m*0.10\ntip = m*0.18\nprint(f"Tax: ${t:.2f}\\nTip: ${tip:.2f}\\nTotal: ${m+t+tip:.2f}")',
    starterCode: '# Tax:10%, Tip:18%\n# Your code here\n',
    hints: ['tax=meal×0.10', 'tip=meal×0.18'],
  },
  // Ex6: Tax and Tip - JavaScript
  {
    title: 'Python Workbook Ch1-Ex6: Tax and Tip',
    description: 'Calculate tax (10%) and tip (18%), then show the total',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['percentage', 'toFixed'],
    tags: ['python-workbook', 'chapter-1', 'exercise-6'],
    testCases: [{ input: '100', expectedOutput: 'Tax: $10.00', description: '$100 meal' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("Meal: ", (m) => {\n    const meal = parseFloat(m);\n    const t = meal*0.10;\n    const tip = meal*0.18;\n    console.log("Tax: $" + t.toFixed(2));\n    console.log("Tip: $" + tip.toFixed(2));\n    console.log("Total: $" + (meal+t+tip).toFixed(2));\n    rl.close();\n});',
    starterCode: '// Tax:10%, Tip:18%\n// Your code here\n',
    hints: ['Multiply by 0.10 and 0.18'],
  },
  // Ex6: Tax and Tip - Java
  {
    title: 'Python Workbook Ch1-Ex6: Tax and Tip',
    description: 'Calculate tax (10%) and tip (18%), then show the total',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['percentage', 'printf'],
    tags: ['python-workbook', 'chapter-1', 'exercise-6'],
    testCases: [{ input: '100', expectedOutput: 'Tax: $10.00', description: '$100 meal' }],
    solution: 'import java.util.Scanner;\n\npublic class TaxTip {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double m = sc.nextDouble();\n        double t = m*0.10;\n        double tip = m*0.18;\n        System.out.printf("Tax: $%.2f%n", t);\n        System.out.printf("Tip: $%.2f%n", tip);\n        System.out.printf("Total: $%.2f%n", m+t+tip);\n        sc.close();\n    }\n}',
    starterCode: '// Tax:10%, Tip:18%\n// Your code here\n',
    hints: ['printf'],
  },
  // Ex6: Tax and Tip - C++
  {
    title: 'Python Workbook Ch1-Ex6: Tax and Tip',
    description: 'Calculate tax (10%) and tip (18%), then show the total',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['percentage', 'setprecision'],
    tags: ['python-workbook', 'chapter-1', 'exercise-6'],
    testCases: [{ input: '100', expectedOutput: 'Tax: $10.00', description: '$100 meal' }],
    solution: '#include <iostream>\n#include <iomanip>\nusing namespace std;\n\nint main() {\n    double m;\n    cin >> m;\n    double t = m*0.10;\n    double tip = m*0.18;\n    cout << fixed << setprecision(2);\n    cout << "Tax: $" << t << endl;\n    cout << "Tip: $" << tip << endl;\n    cout << "Total: $" << (m+t+tip) << endl;\n    return 0;\n}',
    starterCode: '// Tax:10%, Tip:18%\n// Your code here\n',
    hints: ['setprecision'],
  },

  // Ex7: Sum of First n Integers - Python
  {
    title: 'Python Workbook Ch1-Ex7: Sum of First n Integers',
    description: 'Sum 1..n using the formula n(n+1)/2',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['formula', 'sum'],
    tags: ['python-workbook', 'chapter-1', 'exercise-7'],
    testCases: [{ input: '10', expectedOutput: '55', description: '1+2+...+10=55' }],
    solution: 'n = int(input("n: "))\nprint("Sum:", n*(n+1)//2)',
    starterCode: '# Formula: n(n+1)/2\n# Your code here\n',
    hints: ['n*(n+1)//2', 'No loop needed'],
  },
  // Ex7: Sum of First n Integers - JavaScript
  {
    title: 'Python Workbook Ch1-Ex7: Sum of First n Integers',
    description: 'Sum 1..n using the formula n(n+1)/2',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['formula', 'Math.floor'],
    tags: ['python-workbook', 'chapter-1', 'exercise-7'],
    testCases: [{ input: '10', expectedOutput: '55', description: '1+2+...+10=55' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("n: ", (n) => {\n    const num = parseInt(n);\n    console.log("Sum:", Math.floor(num*(num+1)/2));\n    rl.close();\n});',
    starterCode: '// Formula: n(n+1)/2\n// Your code here\n',
    hints: ['Math.floor'],
  },
  // Ex7: Sum of First n Integers - Java
  {
    title: 'Python Workbook Ch1-Ex7: Sum of First n Integers',
    description: 'Sum 1..n using the formula n(n+1)/2',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['formula', 'sum'],
    tags: ['python-workbook', 'chapter-1', 'exercise-7'],
    testCases: [{ input: '10', expectedOutput: '55', description: '1+2+...+10=55' }],
    solution: 'import java.util.Scanner;\n\npublic class SumN {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        System.out.println("Sum: " + (n*(n+1)/2));\n        sc.close();\n    }\n}',
    starterCode: '// Formula: n(n+1)/2\n// Your code here\n',
    hints: ['Integer division'],
  },
  // Ex7: Sum of First n Integers - C++
  {
    title: 'Python Workbook Ch1-Ex7: Sum of First n Integers',
    description: 'Sum 1..n using the formula n(n+1)/2',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['formula', 'sum'],
    tags: ['python-workbook', 'chapter-1', 'exercise-7'],
    testCases: [{ input: '10', expectedOutput: '55', description: '1+2+...+10=55' }],
    solution: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    cout << "Sum: " << (n*(n+1)/2) << endl;\n    return 0;\n}',
    starterCode: '// Formula: n(n+1)/2\n// Your code here\n',
    hints: ['Integer division'],
  },

  // Ex8: Widgets and Gizmos - Python
  {
    title: 'Python Workbook Ch1-Ex8: Widgets and Gizmos',
    description: 'Widget=75g, Gizmo=112g. Calculate the total weight',
    difficulty: 'easy',
    language: 'python',
    category: 'logic-math',
    keywords: ['arithmetic', 'weight'],
    tags: ['python-workbook', 'chapter-1', 'exercise-8'],
    testCases: [{ input: '10\n5', expectedOutput: '1310', description: '10×75+5×112' }],
    solution: 'w = int(input("Widgets: "))\ng = int(input("Gizmos: "))\nprint("Weight:", w*75+g*112, "g")',
    starterCode: '# Widget:75g, Gizmo:112g\n# Your code here\n',
    hints: ['w×75+g×112'],
  },
  // Ex8: Widgets and Gizmos - JavaScript
  {
    title: 'Python Workbook Ch1-Ex8: Widgets and Gizmos',
    description: 'Widget=75g, Gizmo=112g. Calculate the total weight',
    difficulty: 'easy',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['arithmetic', 'weight'],
    tags: ['python-workbook', 'chapter-1', 'exercise-8'],
    testCases: [{ input: '10\n5', expectedOutput: '1310', description: '10×75+5×112' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("W: ", (w) => {\n    rl.question("G: ", (g) => {\n        console.log("Weight:", parseInt(w)*75+parseInt(g)*112, "g");\n        rl.close();\n    });\n});',
    starterCode: '// Widget:75g, Gizmo:112g\n// Your code here\n',
    hints: ['Multiply and add'],
  },
  // Ex8: Widgets and Gizmos - Java
  {
    title: 'Python Workbook Ch1-Ex8: Widgets and Gizmos',
    description: 'Widget=75g, Gizmo=112g. Calculate the total weight',
    difficulty: 'easy',
    language: 'java',
    category: 'logic-math',
    keywords: ['arithmetic', 'weight'],
    tags: ['python-workbook', 'chapter-1', 'exercise-8'],
    testCases: [{ input: '10\n5', expectedOutput: '1310', description: '10×75+5×112' }],
    solution: 'import java.util.Scanner;\n\npublic class WidgetsGizmos {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int w = sc.nextInt();\n        int g = sc.nextInt();\n        System.out.println("Weight: " + (w*75+g*112) + " g");\n        sc.close();\n    }\n}',
    starterCode: '// Widget:75g, Gizmo:112g\n// Your code here\n',
    hints: ['Multiply and add'],
  },
  // Ex8: Widgets and Gizmos - C++
  {
    title: 'Python Workbook Ch1-Ex8: Widgets and Gizmos',
    description: 'Widget=75g, Gizmo=112g. Calculate the total weight',
    difficulty: 'easy',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['arithmetic', 'weight'],
    tags: ['python-workbook', 'chapter-1', 'exercise-8'],
    testCases: [{ input: '10\n5', expectedOutput: '1310', description: '10×75+5×112' }],
    solution: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int w, g;\n    cin >> w >> g;\n    cout << "Weight: " << (w*75+g*112) << " g" << endl;\n    return 0;\n}',
    starterCode: '// Widget:75g, Gizmo:112g\n// Your code here\n',
    hints: ['Multiply and add'],
  },

  // Ex9: Compound Interest - Python
  {
    title: 'Python Workbook Ch1-Ex9: Compound Interest',
    description: '4% annually. Show the balances for years 1, 2, and 3',
    difficulty: 'medium',
    language: 'python',
    category: 'logic-math',
    keywords: ['interest', 'compound'],
    tags: ['python-workbook', 'chapter-1', 'exercise-9'],
    testCases: [{ input: '1000', expectedOutput: 'Year 1: $1040.00', description: '$1000 at 4%' }],
    solution: 'd = float(input("Deposit: "))\ny1 = d*1.04\ny2 = y1*1.04\ny3 = y2*1.04\nprint(f"Y1: ${y1:.2f}\\nY2: ${y2:.2f}\\nY3: ${y3:.2f}")',
    starterCode: '# 4% annually, 3 years\n# Your code here\n',
    hints: ['Year N+1 = Year N × 1.04', '3 calculations'],
  },
  // Ex9: Compound Interest - JavaScript
  {
    title: 'Python Workbook Ch1-Ex9: Compound Interest',
    description: '4% annually. Show the balances for years 1, 2, and 3',
    difficulty: 'medium',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['interest', 'compound'],
    tags: ['python-workbook', 'chapter-1', 'exercise-9'],
    testCases: [{ input: '1000', expectedOutput: 'Year 1: $1040.00', description: '$1000 at 4%' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("D: ", (d) => {\n    let y1 = parseFloat(d)*1.04;\n    let y2 = y1*1.04;\n    let y3 = y2*1.04;\n    console.log("Y1: $" + y1.toFixed(2));\n    console.log("Y2: $" + y2.toFixed(2));\n    console.log("Y3: $" + y3.toFixed(2));\n    rl.close();\n});',
    starterCode: '// 4% annually, 3 years\n// Your code here\n',
    hints: ['Multiplica by 1.04'],
  },
  // Ex9: Compound Interest - Java
  {
    title: 'Python Workbook Ch1-Ex9: Compound Interest',
    description: '4% annually. Show the balances for years 1, 2, and 3',
    difficulty: 'medium',
    language: 'java',
    category: 'logic-math',
    keywords: ['interest', 'compound'],
    tags: ['python-workbook', 'chapter-1', 'exercise-9'],
    testCases: [{ input: '1000', expectedOutput: 'Year 1: $1040.00', description: '$1000 at 4%' }],
    solution: 'import java.util.Scanner;\n\npublic class CompoundInterest {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        double d = sc.nextDouble();\n        double y1 = d*1.04;\n        double y2 = y1*1.04;\n        double y3 = y2*1.04;\n        System.out.printf("Y1: $%.2f%n", y1);\n        System.out.printf("Y2: $%.2f%n", y2);\n        System.out.printf("Y3: $%.2f%n", y3);\n        sc.close();\n    }\n}',
    starterCode: '// 4% annually, 3 years\n// Your code here\n',
    hints: ['Multiplica by 1.04'],
  },
  // Ex9: Compound Interest - C++
  {
    title: 'Python Workbook Ch1-Ex9: Compound Interest',
    description: '4% annually. Show the balances for years 1, 2, and 3',
    difficulty: 'medium',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['interest', 'compound'],
    tags: ['python-workbook', 'chapter-1', 'exercise-9'],
    testCases: [{ input: '1000', expectedOutput: 'Year 1: $1040.00', description: '$1000 at 4%' }],
    solution: '#include <iostream>\n#include <iomanip>\nusing namespace std;\n\nint main() {\n    double d;\n    cin >> d;\n    double y1 = d*1.04;\n    double y2 = y1*1.04;\n    double y3 = y2*1.04;\n    cout << fixed << setprecision(2);\n    cout << "Y1: $" << y1 << endl;\n    cout << "Y2: $" << y2 << endl;\n    cout << "Y3: $" << y3 << endl;\n    return 0;\n}',
    starterCode: '// 4% annually, 3 years\n// Your code here\n',
    hints: ['Multiplica by 1.04'],
  },

  // Ex10: Arithmetic - Python
  {
    title: 'Python Workbook Ch1-Ex10: Arithmetic',
    description: 'Read a and b. Calculate their sum, difference, product, quotient, remainder, log10(a), and a^b',
    difficulty: 'medium',
    language: 'python',
    category: 'logic-math',
    keywords: ['arithmetic', 'math'],
    tags: ['python-workbook', 'chapter-1', 'exercise-10'],
    testCases: [{ input: '10\n3', expectedOutput: 'Sum: 13', description: 'a=10,b=3' }],
    solution: 'import math\na = int(input("a: "))\nb = int(input("b: "))\nprint("Sum:", a+b)\nprint("Diff:", a-b)\nprint("Prod:", a*b)\nprint("Quot:", a/b)\nprint("Rem:", a%b)\nprint("Log:", math.log10(a))\nprint("Pow:", a**b)',
    starterCode: 'import math\n# 7 operations\n# Your code here\n',
    hints: ['7 operations', 'math.log10, **'],
  },
  // Ex10: Arithmetic - JavaScript
  {
    title: 'Python Workbook Ch1-Ex10: Arithmetic',
    description: 'Read a and b. Calculate their sum, difference, product, quotient, remainder, log10(a), and a^b',
    difficulty: 'medium',
    language: 'javascript',
    category: 'logic-math',
    keywords: ['arithmetic', 'Math'],
    tags: ['python-workbook', 'chapter-1', 'exercise-10'],
    testCases: [{ input: '10\n3', expectedOutput: 'Sum: 13', description: 'a=10,b=3' }],
    solution: 'const readline = require("readline");\nconst rl = readline.createInterface({input: process.stdin, output: process.stdout});\nrl.question("a: ", (a) => {\n    rl.question("b: ", (b) => {\n        const x = parseInt(a), y = parseInt(b);\n        console.log("Sum:", x+y);\n        console.log("Diff:", x-y);\n        console.log("Prod:", x*y);\n        console.log("Quot:", x/y);\n        console.log("Rem:", x%y);\n        console.log("Log:", Math.log10(x));\n        console.log("Pow:", Math.pow(x,y));\n        rl.close();\n    });\n});',
    starterCode: '// 7 operations\n// Your code here\n',
    hints: ['Math.log10(), Math.pow()'],
  },
  // Ex10: Arithmetic - Java
  {
    title: 'Python Workbook Ch1-Ex10: Arithmetic',
    description: 'Read a and b. Calculate their sum, difference, product, quotient, remainder, log10(a), and a^b',
    difficulty: 'medium',
    language: 'java',
    category: 'logic-math',
    keywords: ['arithmetic', 'Math'],
    tags: ['python-workbook', 'chapter-1', 'exercise-10'],
    testCases: [{ input: '10\n3', expectedOutput: 'Sum: 13', description: 'a=10,b=3' }],
    solution: 'import java.util.Scanner;\n\npublic class Arithmetic {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        System.out.println("Sum: " + (a+b));\n        System.out.println("Diff: " + (a-b));\n        System.out.println("Prod: " + (a*b));\n        System.out.println("Quot: " + ((double)a/b));\n        System.out.println("Rem: " + (a%b));\n        System.out.println("Log: " + Math.log10(a));\n        System.out.println("Pow: " + Math.pow(a,b));\n        sc.close();\n    }\n}',
    starterCode: '// 7 operations\n// Your code here\n',
    hints: ['Math.log10(), Math.pow()'],
  },
  // Ex10: Arithmetic - C++
  {
    title: 'Python Workbook Ch1-Ex10: Arithmetic',
    description: 'Read a and b. Calculate their sum, difference, product, quotient, remainder, log10(a), and a^b',
    difficulty: 'medium',
    language: 'cpp',
    category: 'logic-math',
    keywords: ['arithmetic', 'cmath'],
    tags: ['python-workbook', 'chapter-1', 'exercise-10'],
    testCases: [{ input: '10\n3', expectedOutput: 'Sum: 13', description: 'a=10,b=3' }],
    solution: '#include <iostream>\n#include <cmath>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << "Sum: " << (a+b) << endl;\n    cout << "Diff: " << (a-b) << endl;\n    cout << "Prod: " << (a*b) << endl;\n    cout << "Quot: " << ((double)a/b) << endl;\n    cout << "Rem: " << (a%b) << endl;\n    cout << "Log: " << log10(a) << endl;\n    cout << "Pow: " << pow(a,b) << endl;\n    return 0;\n}',
    starterCode: '#include <cmath>\n// 7 operations\n// Your code here\n',
    hints: ['log10(), pow()'],
  },
];